name = "rsshub"
main = "dist-worker/worker.mjs"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "lib/assets" }

[build]
command = "pnpm run worker-build"

[[kv_namespaces]]
binding = "CACHE"
id = "ecf63134f36745809da922264f4b3442"

[vars]